# Site settings
title: Python Brasil 12
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  12ª Conferência Brasileira da Comunidade Python. Cinco dias de
  Tutoriais, palestras e sprints sobre a linguagem Python.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pythonbrasil.github.io/pythonbrasil12-site" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
